apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::795743416821:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-ufR4P9TsMgyi
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2023-11-10T22:35:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1298"
  uid: 78af9c03-695b-4d9e-a5a7-967445b6c462
